### Signup
POST http://localhost:3000/signup HTTP/1.1
content-type: application/json

{
  "email": "ramirez@gmail.com",
  "password": "Ramirez1!",
  "confirmation": "Ramirez1!"
}

### Signin
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
  "email": "ramirez@gmail.com",
  "password": "Ramirez1!"
}