### Render all events
GET http://localhost:3000/events

### Render all published events
GET http://localhost:3000/events/published

### Render one event with id
GET http://localhost:3000/event/1

### Render one event with slug
GET http://localhost:3000/event/smash-bros-by-versus

### Create an event
POST http://localhost:3000/event HTTP/1.1
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTcwMjkyNDUwMSwiZXhwIjoxNzAyOTI0NTIxfQ.IGhKDDtWZOJRonMSHJl010oNhCNT8SPwJzEQwzstE2c
refreshtoken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTcwMjkyNDUwMSwiZXhwIjoxNzAyOTI1MTAxfQ.bnOd_s3G57_DMVB9oEu-Rytcaaasc9fZYXDp8EHa2v8

{
    "title": "Smash Bros by VERSUS 6",
    "start_date": "2024-01-01",
    "end_date": "2024-01-01",
    "user_id": 1
}

### Update an event
PATCH http://localhost:3000/event/1 HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlhdCI6MTcwMjg5MDczMSwiZXhwIjoxNzAyOTc3MTMxfQ.a1KaVpCgLJ1xpLebG1I-nO60J1NgTW_dOT-9qbmroEI

{
    "status": "published"
}

### Delete one event
DELETE  http://localhost:3000/event/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlhdCI6MTcwMjg5MDczMSwiZXhwIjoxNzAyOTc3MTMxfQ.a1KaVpCgLJ1xpLebG1I-nO60J1NgTW_dOT-9qbmroEI


### Register to an event
PATCH http://localhost:3000/event/4/register HTTP/1.1
content-type: application/json

{
    "user_id": 2
}

### Unregister from an event
PATCH http://localhost:3000/event/4/unregister HTTP/1.1
content-type: application/json

{
    "user_id": 2
}