### Render all events
GET http://localhost:3000/events

### Render one event
GET http://localhost:3000/event/4

### Create an event
POST http://localhost:3000/event HTTP/1.1
content-type: application/json

{
    "title": "Smash Bros by VERSUS",
    "start_date": "2024-01-01",
    "end_date": "2024-01-01",
    "status": "draft"
}

### Update an event
PATCH http://localhost:3000/event/4 HTTP/1.1
content-type: application/json

{
    "location": "En ligne",
    "description": "Tournoi VERSUS Smash Bros",
    "contact": "ramirez@versus.gg",
    "game_id": 4,
    "type_event_id": 1
}

### Delete one event
DELETE  http://localhost:3000/event/5

### Register to an event
PATCH http://localhost:3000/event/4/register HTTP/1.1
content-type: application/json

{
    "user_id": 2
}

### Unregister from an event
PATCH http://localhost:3000/event/4/unregister HTTP/1.1
content-type: application/json

{
    "user_id": 2
}