### Render all events
GET http://localhost:3000/event

### Render one event
GET http://localhost:3000/event/4

### Create an event
POST http://localhost:3000/event HTTP/1.1
content-type: application/json

{
    "title": "Tournoi Mario Kart",
    "start_date": "2023-12-12",
    "end_date": "2023-12-13",
    "status": "draft"
}

### Update an event
PATCH http://localhost:3000/event/3 HTTP/1.1
content-type: application/json

{
    "location": "Chez moi",
    "type_event_id": 1
}

### Delete one event
DELETE  http://localhost:3000/event/4

### Register to an event
PATCH http://localhost:3000/event/4/register HTTP/1.1
content-type: application/json

{
    "user_id": 2
}