### Render all teams
GET http://localhost:3000/teams

### Render one team
GET http://localhost:3000/team/2

### Create a team
POST http://localhost:3000/team HTTP/1.1
content-type: application/json

{
    "name": "Cheesecake"
}

### Update one team
PATCH http://localhost:3000/team/2 HTTP/1.1
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcwMzAxODY5NCwiZXhwIjoxNzAzMTA1MDk0fQ.huCNoJaOM965efoUyXjFPp_PeuS5Q0tk90CWptzUGP4
refreshtoken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcwMzAxODY5NCwiZXhwIjoxNzA1NjEwNjk0fQ.l3gjMhBJkgj6RgY-Q3Eoxuypyxbunx7pJ9K7AX34R34

{
    "name": "Le 18ème"
}

### Delete one event
DELETE  http://localhost:3000/team/3

### Update user of a team
PATCH http://localhost:3000/team/2/user HTTP/1.1
content-type: application/json

{
    "user_id": 2
}