BEGIN;

DROP TABLE IF EXISTS 
"role", 
"user", 
"social", 
"team", 
"platform", 
"game", 
"type_event",
"event",
"user_has_team",
"user_like_team",
"user_like_user",
"user_like_platform",
"user_like_game",
"game_has_platform",
"event_has_user",
"event_has_team";

CREATE TABLE "role" (
  "id" SERIAL PRIMARY KEY,
  "name" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "user" (
  "id" SERIAL PRIMARY KEY,
  "username" TEXT NOT NULL UNIQUE,
  "email" TEXT NOT NULL UNIQUE,
  "password" TEXT NOT NULL,
  "avatar" TEXT,
  "role_id" INTEGER REFERENCES "role"("id") ON DELETE CASCADE,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "social" (
  "id" SERIAL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "link" TEXT NOT NULL,
  "user_id" INTEGER REFERENCES "user"("id") ON DELETE CASCADE,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "team" (
  "id" SERIAL PRIMARY KEY,
  "name" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "platform" (
  "id" SERIAL PRIMARY KEY,
  "name" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "game" (
  "id" SERIAL PRIMARY KEY,
  "name" TEXT,
  "thumbnail" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "type_event" (
  "id" SERIAL PRIMARY KEY,
  "name" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "event" (
  "id" SERIAL PRIMARY KEY,
  "title" TEXT NOT NULL,
  "title_slug" TEXT,
  "start_date" DATE NOT NULL,
  "end_date" DATE NOT NULL,
  "banner" TEXT,
  "thumbnail" TEXT,
  "location" TEXT,
  "status" TEXT DEFAULT 'draft' NOT NULL,
  "description" TEXT,
  "rules" TEXT,
  "contact" TEXT,
  "type_event_id" INTEGER REFERENCES "type_event"("id") ON DELETE CASCADE,
  "game_id" INTEGER REFERENCES "game"("id") ON DELETE CASCADE,
  "user_id" INTEGER REFERENCES "user"("id") ON DELETE CASCADE,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "user_has_team" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" INTEGER NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "team_id" INTEGER NOT NULL REFERENCES "team"("id") ON DELETE CASCADE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "user_like_team" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" INTEGER NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "team_id" INTEGER NOT NULL REFERENCES "team"("id") ON DELETE CASCADE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "user_like_user" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" INTEGER NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "user_liked_id" INTEGER NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "user_like_platform" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" INTEGER NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "platform_id" INTEGER NOT NULL REFERENCES "platform"("id") ON DELETE CASCADE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "user_like_game" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" INTEGER NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "game_id" INTEGER NOT NULL REFERENCES "game"("id") ON DELETE CASCADE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "game_has_platform" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "game_id" INTEGER NOT NULL REFERENCES "game"("id") ON DELETE CASCADE,
    "platform_id" INTEGER NOT NULL REFERENCES "platform"("id") ON DELETE CASCADE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "event_has_user" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "event_id" INTEGER NOT NULL REFERENCES "event"("id") ON DELETE CASCADE,
    "user_id" INTEGER NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "event_has_team" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "event_id" INTEGER NOT NULL REFERENCES "event"("id") ON DELETE CASCADE,
    "team_id" INTEGER NOT NULL REFERENCES "team"("id") ON DELETE CASCADE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMIT;
